AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - Appraisals

Naming/FileName:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false